name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Cache Boost
      uses: actions/cache@v2
      with:
        path: '${{ runner.workspace }}/boost_*.tar.gz'
        key: 'boost-1.72.0'
    - name: Build Boost
      # This won't re-download the archive unnecessarily:
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.82.0
    - name: Build Compiler
      run: make
